"""Schema 2 → schema 3, derived offline (parsing contract v3 §7).

The whole v20 bump rests on this module: a corpus extracted under
`demand-profile/v10` / schema 2 has to reach schema 3 without a single engine
call, or the migration is a re-extraction and the cost of the contract change
is the cost of the corpus. Two pure derivations do it — one for an archived
emit, one for an archived record — and they agree, because the fixture corpus
is regenerated by the first and the live archive is replayed by the second.

What the derivation may NOT do is carry the removed verdict across under
another name. `importance` was a label the model read off descriptor text
("Demonstrable expertise" → required), and schema 3 removed it precisely
because nothing in the source could check it. So only the quote survives, and
only when the quote itself carries one of the code-owned modal terms below:
anything else derives null. The lexicon is deliberately code-owned and closed
HERE — the live contract's `modality_evidence` vocabulary is open (§2.1, the
validator checks binding, not wording), but a *derivation* that accepted any
quote would be re-labelling history rather than reading it.

Mechanical is the point: the rule is substring containment over the archived
quote, so a quote that happens to be a section heading ("What We Require")
derives a modality the live contract would not have asked the model for. That
is the honest reading of what the archive holds — the quote is what the
extractor cited as its reason — and pretending otherwise would need a judgment
call this module has no source for.

Pure like every other `l2/v2` module: no I/O, no environment, no store imports.
"""

from __future__ import annotations

import copy
from typing import Any

from jobhunter.l2.v2.assemble import candidate_hash, section_heading
from jobhunter.l2.v2.facts import VALIDATOR_VERSION
from jobhunter.l2.v2.types import Block
from jobhunter.l2.v2.verify import evidence_blocks

#: The shape this derivation produces, written as a literal because there is no
#: canonical constant to import: every `l2/v2` module carries its own frozen
#: shape identity (`assemble.SCHEMA_VERSION` is still "2", the shape assembly
#: defaults to), and the authority on what the ACTIVE bundle runs is
#: `bundles.py`. This constant names the target of the derivation, nothing else.
SCHEMA_VERSION = "3"

#: The shape this derivation accepts. Only one: reading a schema-3 object as if
#: it were schema 2 erases modality silently (`_require_schema2`).
SOURCE_SCHEMA_VERSION = "2"

#: The code-owned modal lexicon (spec §7). Casefolded substring containment:
#: "require" catches "requires"/"requirement", "plus" catches "a plus", and
#: "must" catches "Must have". Order is the spec's, so the list reads as the
#: spec does.
MODAL_LEXICON: tuple[str, ...] = (
    "must", "required", "require", "preferred", "prefer", "ideally",
    "plus", "nice to have", "bonus", "minimum", "at least", "strongly",
)

#: The schema-2 statement fields schema 3 removed, and their evidence. Schema 2
#: requires all four and schema 3 forbids all four (`additionalProperties:
#: false` on both), so their presence is also the shape discriminator
#: `_require_schema2` reads.
_VERDICTS = ("importance", "importance_evidence", "proficiency", "proficiency_evidence")


class MigrateError(Exception):
    """This is not a schema-2 object, so there is no derivation to run.

    Refusing matters more here than in most places because the failure mode is
    silent: `_statement3` reads `importance_evidence`, a schema-3 statement has
    none, so a re-derivation would leave every `modality_evidence` null and
    still produce a schema-valid schema-3 object — and on the record path a
    freshly stamped and re-hashed one that verifies clean. Nothing downstream
    could tell that from an honest derivation, so the refusal has to happen at
    the boundary.
    """

    def __init__(self, message: str) -> None:
        super().__init__(message)
        self.message = message


def _require_schema2(statements: list[dict[str, Any]] | None) -> None:
    """Every statement carries the schema-2 verdict fields, or this is not a
    schema-2 object.

    An emit with no statements is a legitimate schema-2 emit (an unusable
    source emits none) and there is nothing to erase, so it passes.
    """
    for statement in statements or []:
        missing = [field for field in _VERDICTS if field not in statement]
        if missing:
            raise MigrateError(
                f"statement {statement.get('id')!r} is not schema 2: "
                f"missing {', '.join(missing)}"
            )


def quotes_modality(text: str | None) -> bool:
    """True when this quoted text carries one of the modal terms.

    `None` — an unbound whole-block reference read without its annotation — is
    not a match: the text is unknown, and unknown is null, never a guess.
    """
    if not text:
        return False
    folded = text.casefold()
    return any(term in folded for term in MODAL_LEXICON)


def _modality_of(
    refs: list[dict[str, Any]] | None, texts: dict[str, str] | None
) -> list[dict[str, Any]] | None:
    """The one archived reference that quotes a modal phrase, or None.

    Schema 3 admits exactly one modality reference (`maxItems: 1`) while
    schema 2's `importance_evidence` was an evidence array, so the first
    matching reference in the archived order is the one that survives —
    deterministic, and the only reading that does not silently drop a document
    whose extractor cited two.

    `texts` maps block id → block text, for references that quote a whole block
    (`text: null`) and therefore carry their quote in the annotation rather
    than in the reference. A bound record reference always materialises its
    text, so the record path never needs it.
    """
    for ref in refs or []:
        quoted = ref.get("text")
        if quoted is None and texts is not None:
            quoted = texts.get(str(ref.get("block_id")))
        if quotes_modality(quoted if isinstance(quoted, str) else None):
            return [copy.deepcopy(ref)]
    return None


def _statement3(
    statement: dict[str, Any],
    *,
    texts: dict[str, str] | None,
    blocks: list[Block] | None,
) -> dict[str, Any]:
    """One statement in the schema-3 shape, in the schema's own field order.

    Built explicitly rather than by deleting keys so a migrated statement is
    byte-identical to an assembled one: the record is hashed as canonical JSON,
    but the ARCHIVED attempt is stored as written, and a corpus whose migrated
    fixtures differ from freshly assembled ones only in key order is a corpus
    no diff can be read against.

    `blocks is None` builds the EMIT shape (no `section_heading`: code owns it,
    and schema 3 rejects an emitted one); a block list builds the RECORD shape.
    """
    derived: dict[str, Any] = {
        "id": statement.get("id"),
        "kind": statement.get("kind"),
        "subject": statement.get("subject"),
        "topic": statement.get("topic"),
        "evidence": copy.deepcopy(statement.get("evidence")),
    }
    if blocks is not None:
        derived["section_heading"] = section_heading(blocks, derived["evidence"] or [])
    derived["modality_evidence"] = _modality_of(statement.get("importance_evidence"), texts)
    derived["polarity"] = statement.get("polarity")
    derived["polarity_evidence"] = copy.deepcopy(statement.get("polarity_evidence"))
    derived["condition_ids"] = list(statement.get("condition_ids") or [])
    derived["fact_ids"] = list(statement.get("fact_ids") or [])
    derived["unresolved"] = copy.deepcopy(statement.get("unresolved") or [])
    return derived


def _reaccounted(
    entries: list[dict[str, Any]] | None,
    before: dict[str, set[str]],
    after: dict[str, set[str]],
) -> list[dict[str, Any]]:
    """Block accounting, with the coverage claims THIS derivation un-evidenced
    re-disposed as `context` rows.

    Schema 2 let a block be covered by any of four reference families, and
    schema 3 keeps two of them: a `statements` row whose only proof was the
    statements' `importance_evidence` (or `proficiency_evidence`) is a claim the
    derived record can no longer support, and `accounting:coverage_unevidenced`
    (validator/19) fails it — which is how 6,534 documents that verified clean
    under schema 2 lost their migrated row entirely in the 2026-09-23 replay.

    The re-disposition is not an invention; it is the contract's own reading of
    the same block. The v10 prompt's worked example accounts the heading
    "Requirements" as `{"disposition": "statements", "ref_ids": ["s1","s2","s3"]}`
    *because this heading is what carries those statements' importance*, and the
    v11 example makes that very block `{"disposition": "context", "ref_ids": []}`
    *because a heading is never quoted as a statement's modality*. The block was
    read and produced no object of its own: that is what `context` says, and the
    requirement-language tripwire (`context_requirement_language`) then points
    the auditor at any such block that still speaks in obligations, which is
    exactly where the question belongs.

    Only rows the derivation itself moved: a claim the archived record already
    failed to evidence under schema 2 is carried through untouched, because
    rewriting it would hide an extraction defect behind a migration. `before`
    and `after` are the coverage index `verify` checks against
    (`verify.evidence_blocks`), read under the source and target schema versions
    — the check and the derivation cannot drift apart because they are the same
    function.
    """
    derived: list[dict[str, Any]] = []
    for entry in entries or []:
        row = copy.deepcopy(entry)
        ref_ids = row.get("ref_ids") or []
        block_id = row.get("block_id")
        if row.get("disposition") in ("statements", "facts") and ref_ids:
            covered = any(block_id in after.get(ref, frozenset()) for ref in ref_ids)
            was_covered = any(block_id in before.get(ref, frozenset()) for ref in ref_ids)
            if was_covered and not covered:
                row["disposition"] = "context"
                row["ref_ids"] = []
        derived.append(row)
    return derived


def emit3_of(emit: dict[str, Any], *, blocks: list[Block] | None = None) -> dict[str, Any]:
    """A schema-2 emit's schema-3 form: verdicts out, quoted modality in.

    Everything outside `statements` is the same object — mentions, facts,
    relations, areas and block accounting are byte-for-byte the schema-2 shapes
    (spec §2.2), so they are carried through rather than rebuilt.

    `blocks` is the document's annotation, and it is optional for one reason:
    an emit's reference may quote a WHOLE block (`text: null`), and the quote
    then lives in the document, not in the emit. Given the annotation, such a
    reference is read and can derive a modality; without it the quote is
    unknown and derives null. Callers that have the source — the fixture
    regeneration, any replay of an archived emit — pass it.

    The input is never mutated, and an input that is not schema 2 raises
    `MigrateError` rather than deriving a modality-free schema-3 emit.
    """
    _require_schema2(emit.get("statements"))
    derived = copy.deepcopy(emit)
    texts = {block.id: block.text for block in blocks} if blocks is not None else None
    derived["statements"] = [
        _statement3(statement, texts=texts, blocks=None)
        for statement in emit.get("statements") or []
    ]
    # on the ids the EMIT names, which is all an unbound shape can answer with.
    # Assembly may re-anchor a reference to another block (parsing-rules/3), so
    # the record path re-accounts on the bound ids and is the authority; doing
    # it here too is what keeps the two paths landing on one candidate for the
    # fixture corpus (`scripts/migrate_cases_v3.py`).
    derived["block_accounting"] = _reaccounted(
        emit.get("block_accounting"),
        evidence_blocks(emit, SOURCE_SCHEMA_VERSION),
        evidence_blocks(derived, SCHEMA_VERSION),
    )
    return derived


def record3_of(record: dict[str, Any], blocks: list[Block]) -> dict[str, Any]:
    """A schema-2 record's schema-3 form, re-sealed under validator 20.

    The bound references are the archived ones: migration re-shapes a record,
    it never re-binds it, so every span the schema-2 record proved still points
    where it pointed. What IS re-derived is what code owns — `section_heading`
    through assembly's own derivation (never a second copy of the rule, which
    is what `verify` re-derives against) and the candidate hash, because the
    hash covers the record's shape and a migrated candidate is a different
    candidate.

    And the block accounting rows whose proof the derivation itself retired
    (`_reaccounted`): dropping `importance_evidence` drops the only reference a
    heading row's coverage claim ever stood on, and leaving the claim behind is
    a record that fails the check it verified under one shape earlier. Spec §2.2
    still holds — block accounting is byte-for-byte schema 2's — for every row
    whose evidence survives the bump, which is every row but this one shape.

    `extraction` keeps the extraction's own provenance — model, prompt version,
    timestamp, parent link — and moves only the two identifiers that describe
    the SHAPE: the schema version it now is, and the validator that now judges
    it. The prompt version is history: `demand-profile/v10` is what ran, and
    stamping v11 on a record no v11 prompt produced would put a lie in the
    provenance chain. The caller that files the derived record decides which
    tuple's partition it belongs to.

    The input is never mutated, and a record whose envelope does not declare
    schema 2 raises `MigrateError`. The envelope is the authority rather than
    the statement shape because a record HAS one and it is what routes the
    record everywhere else (`rebuild` groups attempts by it): a replay that
    hands this function a schema-3 record has mis-routed, and the derivation
    that would follow — null modality, new stamp, new hash, verifies clean —
    is indistinguishable from a real one.
    """
    declared = (record.get("extraction") or {}).get("schema_version")
    if declared != SOURCE_SCHEMA_VERSION:
        raise MigrateError(
            f"record declares schema {declared!r}, not schema {SOURCE_SCHEMA_VERSION}"
        )
    _require_schema2(record.get("statements"))
    derived = copy.deepcopy(record)
    derived["statements"] = [
        _statement3(statement, texts=None, blocks=blocks)
        for statement in record.get("statements") or []
    ]
    derived["block_accounting"] = _reaccounted(
        record.get("block_accounting"),
        evidence_blocks(record, SOURCE_SCHEMA_VERSION),
        evidence_blocks(derived, SCHEMA_VERSION),
    )
    extraction = derived.setdefault("extraction", {})
    extraction["schema_version"] = SCHEMA_VERSION
    extraction["validator_version"] = VALIDATOR_VERSION
    extraction["candidate_hash"] = ""
    extraction["candidate_hash"] = candidate_hash(derived)
    return derived
